### ISSUE TITLE
Uncaught (in promise) Error: Prop client id required since plugin is not initialized with a client id

### ISSUE THREAD

**Issue by kendrick-fnw** [HugoRCD/nuxtjs-boilerplate#18]
Hi, thank you! 
On Mac : Uncaught (in promise) Error: Prop client id required since plugin is not initialized with a client id 
though .env is set with a GOOGLE_CLIENT_ID
any ideas please?

**Comment by HugoRCD** [comment]
Hi Kendrick can you give me more information about your configuration, the nuxt.config.ts file etc...
Did the error happen just by cloning the repo or did you make any changes?

**Comment by kendrick-fnw** [comment]
thanks, just cloning and setting the .env

**Comment by HugoRCD** [comment]
I just fixed the problem I had forgotten to update the .env.example,
For the environment variable to work you have to put NUXT in front of GOOGLE_CLIENT_ID -> NUXT_GOOGLE_CLIENT_ID

**Comment by kendrick-fnw** [comment]
Thank you!! It works, now I'm missing what I should put here APP_API_URL = ?

**Comment by HugoRCD** [comment]
This variable is used to connect a backend, I have a NestJS template that adds the authentication system to this Nuxt template.
If you don't have a backend this variable is useless

**Comment by HugoRCD** [comment]
Do you have more information? I don't see where it is

**Comment by kendrick-fnw** [comment]
After http://localhost:3000/app/signup : xhr.js:247 POST http://localhost:3000/app/auth/google 404 (Page not found: /app/auth/google)

**Comment by HugoRCD** [comment]
I made a lot of changes since then, the boilerplate is not linked to the API anymore, look at the readme everything is explained and come back to me if you have any questions

**Comment by kendrick-fnw** [comment]
updating I have a 500 like here : https://nuxtapp.maisonhochard.com/

**Comment by HugoRCD** [comment]
The preview is no longer active here
You can check the new preview here https://nuxtjs-boilerplate-mu.vercel.app/
But the Supabase URL is configure for the localhost for the moment so you have to wait until I finish all the switch to supabase
